#
# Stage 1: Build filestash
#

FROM debian:stable-slim AS build
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y golang npm curl

RUN apt-get install -y libglib2.0-dev make git

COPY . /src


#
# Prepare Build
#

WORKDIR /src
RUN \
    mkdir -p ./dist/data/state/config && \
    cp config/config.json ./dist/data/state/config/ && \
    mkdir -p ./filestash/data/state/config && \
    cp config/config.json ./filestash/data/state/config/

#
# Build backend
#

WORKDIR /src/server/plugin/plg_image_light/deps
RUN ./create_libresize.sh
RUN ./create_libtranscode.sh
RUN cp libtranscode.a libtranscode_`uname -s`-`uname -m`.a
RUN cp libresize.a libresize_`uname -s`-`uname -m`.a

#RUN make build_init
RUN make build_backend
RUN cp dist/filestash filestash/
RUN chmod -R o+r+w+x ./dist/data

#
# Build Frontend
#

RUN npm install --silent --include=dev --force
RUN make build_frontend
RUN cp -R ./dist/data/public ./filestash/data/public

RUN chmod -R o-r-w-x- ./filestash

#
# Stage 2: Build final Docker Image
#

FROM debian:stable-slim
MAINTAINER mickael@kerjean.me

ENV DEBIAN_FRONTEND noninteractive

RUN mkdir -p /app
COPY --from=build /src/filestash /app/filestash

# org-mode: html export
COPY server/.assets/emacs/htmlize.el /usr/share/emacs/site-lisp/htmlize.el

# org-mode: markdown export
COPY server/.assets/emacs/ox-gfm.el  /usr/share/emacs/site-lisp/ox-gfm.el

RUN apt-get update > /dev/null && \
    #################
    # Optional dependencies
    apt-get install -y curl tor emacs-nox ffmpeg zip poppler-utils > /dev/null && \
    # org-mode: pdf export (with a light latex distribution)
    cd && apt-get install -y wget perl > /dev/null && \
    export CTAN_REPO="http://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet" && \
    curl -sL "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh && \
    mv ~/.TinyTeX /usr/share/tinytex && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install wasy && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install ulem && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install marvosym && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install wasysym && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install xcolor && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install listings && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install parskip && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install float && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install wrapfig && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install sectsty && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install capt-of && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install epstopdf-pkg && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install cm-super && \
    ln -s /usr/share/tinytex/bin/x86_64-linux/pdflatex /usr/local/bin/pdflatex && \
    apt-get purge -y --auto-remove perl wget && \
    # Cleanup
    find /usr/share/ -name 'doc' | xargs rm -rf && \
    find /usr/share/emacs -name '*.pbm' | xargs rm -f && \
    find /usr/share/emacs -name '*.png' | xargs rm -f && \
    find /usr/share/emacs -name '*.xpm' | xargs rm -f && \
    #################
    # Finalise the image
    useradd filestash && \
    chown -R filestash:filestash /app/ && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

USER filestash
RUN timeout 1 /app/filestash | grep -q start

EXPOSE 8334
VOLUME ["/app/data/state/"]
WORKDIR "/app"
CMD ["/app/filestash"]
