#
# Stage 1: Build filestash
#

FROM debian:unstable-slim AS build
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    golang npm curl libglib2.0-dev libpangoft2-1.0-0 make git \
    curl make gcc g++ xz-utils pkg-config python3-pip autoconf libtool unzip python-setuptools cmake git \
    libraw-dev libjpeg-dev libgcc-11-dev libvips-dev

#
# Prepare deps
#

COPY server/plugin/plg_image_light/deps /deps
WORKDIR /deps
RUN ./create_libtranscode.sh
RUN ./create_libresize.sh
RUN cp libtranscode.a libtranscode_linux_$(dpkg --print-architecture).a
RUN cp libresize.a libresize_linux_$(dpkg --print-architecture).a

#
# Prepare Build
#

COPY . /src

WORKDIR /src
RUN \
    mkdir -p ./dist/data/state/config && \
    cp config/config.json ./dist/data/state/config/ && \
    mkdir -p ./filestash/data/state/config && \
    cp config/config.json ./filestash/data/state/config/

#
# Build backend
#

# relocation R_X86_64_PC32 against symbol `memset@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIE
#WORKDIR /src/server/plugin/plg_image_light/deps
#RUN ./create_libresize.sh
#RUN ./create_libtranscode.sh
#RUN cp libtranscode.a libtranscode_`uname -s`-`uname -m`.a
#RUN cp libresize.a libresize_`uname -s`-`uname -m`.a
#RUN /src/server/plugin/plg_image_light/install.sh

RUN go generate -x ./server/...

WORKDIR /src
#RUN make build_init
# When the GNU linker sees a library (-l), it discards all symbols that it
# doesn't need. In case a .o or .a file is after a -l flag, the symbols from
# the library are discarded before the object file is considered.
RUN make GOFLAGS="" CGO_LDFLAGS="-L/deps -L/src/server/plugin/plg_image_light/deps -L/usr/lib/x86_64-linux-gnu/ -l:libresize_linux_$(dpkg --print-architecture).a -l:libtranscode_linux_$(dpkg --print-architecture).a  -l:libXext.a -l:libc.a -l:libfreetype.a -l:libopenjp2.a -no-pie -lm -lpthread -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -ldl -l:libzstd.so.1 -ldeflate $(pkg-config --libs --static gio-2.0 pango cairo) -lwebp" build_backend
#RUN make CGO_LDFLAGS="-no-pie -lm -lpthread -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -ldl -L/deps -L/src/server/plugin/plg_image_light/deps -l:libresize.a -l:libtranscode.a" build_backend
RUN ldd dist/filestash
RUN cp dist/filestash filestash/
RUN chmod -R o+r+w+x ./dist/data

#
# Build Frontend
#

RUN npm install --silent --include=dev --force
RUN make build_frontend
RUN cp -R ./dist/data/public ./filestash/data/public

RUN chmod -R o-r-w-x- ./filestash

#
# Stage 2: Build final Docker Image
#

FROM debian:stable-slim
MAINTAINER mickael@kerjean.me

ENV DEBIAN_FRONTEND noninteractive

RUN mkdir -p /app
COPY --from=build /src/filestash /app/filestash

# org-mode: html export
COPY server/.assets/emacs/htmlize.el /usr/share/emacs/site-lisp/htmlize.el

# org-mode: markdown export
COPY server/.assets/emacs/ox-gfm.el  /usr/share/emacs/site-lisp/ox-gfm.el

RUN apt-get update > /dev/null && \
    #################
    # Optional dependencies
    apt-get install -y curl tor emacs-nox ffmpeg zip poppler-utils > /dev/null && \
    # org-mode: pdf export (with a light latex distribution)
    cd && apt-get install -y wget perl > /dev/null && \
    export CTAN_REPO="http://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet" && \
    curl -sL "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh && \
    mv ~/.TinyTeX /usr/share/tinytex && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install wasy && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install ulem && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install marvosym && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install wasysym && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install xcolor && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install listings && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install parskip && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install float && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install wrapfig && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install sectsty && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install capt-of && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install epstopdf-pkg && \
    /usr/share/tinytex/bin/x86_64-linux/tlmgr install cm-super && \
    ln -s /usr/share/tinytex/bin/x86_64-linux/pdflatex /usr/local/bin/pdflatex && \
    apt-get purge -y --auto-remove perl wget && \
    # Cleanup
    find /usr/share/ -name 'doc' | xargs rm -rf && \
    find /usr/share/emacs -name '*.pbm' | xargs rm -f && \
    find /usr/share/emacs -name '*.png' | xargs rm -f && \
    find /usr/share/emacs -name '*.xpm' | xargs rm -f && \
    #################
    # Finalise the image
    useradd filestash && \
    chown -R filestash:filestash /app/ && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

USER filestash
RUN timeout 1 /app/filestash | grep -q start

EXPOSE 8334
VOLUME ["/app/data/state/"]
WORKDIR "/app"
CMD ["/app/filestash"]
